CalibreWebCompanion/CalibreWebCompanion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('library.urls')),
    path('', RedirectView.as_view(url='books/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# if settings.DEBUG: # DEBUG purposes
#     urlpatterns+= [path('silk/', include('silk.urls', namespace='silk'))]
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

CalibreWebCompanion/library/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
import logging

logger = logging.getLogger(__name__)

urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('publishers/', views.PublisherListView.as_view(), name='publishers'),
    path('ratings/', views.RatingListView.as_view(), name='ratings'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('series/', views.SeriesListView.as_view(), name='series'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(),
         name='author-detail-view'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail-view'),
    path('publisher/<int:pk>', views.PublisherDetailView.as_view(),
         name='publisher-detail-view'),
    path('rating/<int:pk>', views.RatingDetailView.as_view(),
         name='rating-detail-view'),
    path('series/<int:pk>', views.SeriesDetailView.as_view(),
         name='series-detail-view'),
    path('tag/<int:pk>', views.TagDetailView.as_view(), name='tag-detail-view'),

    path('results/', views.ResultsView.as_view(), name='results'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('accounts/sign_up/', views.sign_up, name="sign-up")


]

CalibreWebCompanion/library/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
import logging

logger = logging.getLogger(__name__)

class Author(models.Model):
    name = models.TextField()
    sort = models.TextField(blank=True, null=True)
    link = models.TextField()

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('author-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name

    class Meta:
        managed = False
        db_table = 'authors'


class Comment(models.Model):
    book = models.ForeignKey("Book", db_column="book",
                             on_delete=models.CASCADE)
    text = models.TextField()

    class Meta:
        managed = False
        db_table = 'comments'
        indexes = [
            models.Index(fields=["book"], name="comments_idx"),
        ]


class Data(models.Model):
    book = models.IntegerField()
    format = models.TextField()
    uncompressed_size = models.IntegerField()
    name = models.TextField()

    class Meta:
        managed = False
        db_table = 'data'
        indexes = [
            models.Index(fields=["format"], name="formats_idx"),
            models.Index(fields=["book"], name="data_idx"),
        ]


class Identifier(models.Model):
    book = models.ForeignKey("Book", db_column="book", on_delete=models.CASCADE)
    type = models.TextField()
    val = models.TextField()

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.val

    class Meta:
        managed = False
        db_table = 'identifiers'


class Language(models.Model):
    lang_code = models.TextField()

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('language-detail-view', args=[str(self.lang_code)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.lang_code

    class Meta:
        managed = False
        db_table = 'languages'
        indexes = [
            models.Index(fields=["lang_code"], name="languages_idx"),
        ]


class Publisher(models.Model):
    name = models.TextField()
    sort = models.TextField(blank=True, null=True)
    released = models.ManyToManyField(
        "Book",
        through='BookPublisherLink',
        through_fields=('publisher', 'book'),
        related_name="released"
    )

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('publisher-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name

    class Meta:
        managed = False
        db_table = 'publishers'
        indexes = [
            models.Index(fields=["name"], name="publishers_idx"),
        ]


class Rating(models.Model):
    rating = models.IntegerField(blank=True, null=True)

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('rating-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return str(self.rating)

    class Meta:
        managed = False
        db_table = 'ratings'


class Series(models.Model):
    name = models.TextField()
    sort = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('series-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name

    class Meta:
        managed = False
        db_table = 'series'
        indexes = [
            models.Index(fields=["name"], name="series_idx"),
        ]


class Tag(models.Model):
    name = models.TextField()

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('tag-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.name

    class Meta:
        managed = False
        db_table = 'tags'
        indexes = [
            models.Index(fields=["name"], name="tags_idx"),
        ]


class Book(models.Model):
    title = models.TextField()
    sort = models.TextField(blank=True, null=True)
    # This field type is a guess.
    timestamp = models.DateTimeField(blank=True, null=True)
    # This field type is a guess.
    pubdate = models.DateTimeField(blank=True, null=True)
    series_index = models.FloatField()
    author_sort = models.TextField(blank=True, null=True)
    isbn = models.TextField(blank=True, null=True)
    lccn = models.TextField(blank=True, null=True)
    path = models.TextField()
    flags = models.IntegerField()
    uuid = models.TextField(blank=True, null=True)
    has_cover = models.BooleanField(blank=True, null=True)
    last_modified = models.DateTimeField()  # This field type is a guess.
    authors = models.ManyToManyField(
        Author,
        through='BookAuthorLink',
        through_fields=('book', 'author'))
    languages = models.ManyToManyField(
        Language,
        through='BookLanguageLink',
        through_fields=('book', 'lang_code'))

    @property
    def language(self):
        return self.languages.first()

    publishers = models.ManyToManyField(
        Publisher,
        through='BookPublisherLink',
        through_fields=('book', 'publisher'))

    @property
    def publisher(self):
        return self.publishers.first()

    series = models.ManyToManyField(
        Series,
        through='BookSeriesLink',
        through_fields=('book', 'series'))

    @property
    def serie(self):
        return self.series.first()
    tags = models.ManyToManyField(
        Tag,
        through='BookTagLink',
        through_fields=('book', 'tag'))
    ratings = models.ManyToManyField(
        Rating,
        through='BookRatingLink',
        through_fields=('book', 'rating'))

    @cached_property
    def rating(self):
        return self.ratings.first()

    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('book-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title

    class Meta:
        managed = False
        db_table = 'books'
        indexes = [
            models.Index(fields=["sort"], name="books_idx"),
            models.Index(fields=["author_sort"], name="authors_idx"),
        ]


class BookAuthorLink(models.Model):
    book = models.ForeignKey(Book, db_column="book", on_delete=models.CASCADE)
    author = models.ForeignKey(
        Author, db_column="author", on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'books_authors_link'
        indexes = [
            models.Index(fields=["book"], name="books_authors_link_bidx"),
            models.Index(fields=["author"], name="books_authors_link_aidx"),
        ]


class BookLanguageLink(models.Model):
    book = models.ForeignKey(Book, db_column="book", on_delete=models.CASCADE)
    lang_code = models.ForeignKey(
        Language, db_column="lang_code", on_delete=models.CASCADE)
    item_order = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'books_languages_link'
        indexes = [
            models.Index(fields=["book"], name="books_languages_link_bidx"),
            models.Index(fields=["lang_code"],
                         name="books_languages_link_aidx"),
        ]


class BookPublisherLink(models.Model):
    book = models.ForeignKey(Book, db_column="book", on_delete=models.CASCADE)
    publisher = models.ForeignKey(
        Publisher, db_column="publisher", on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'books_publishers_link'
        indexes = [
            models.Index(fields=["book"], name="books_publishers_link_bidx"),
            models.Index(fields=["publisher"],
                         name="books_publishers_link_aidx"),
        ]


class BookRatingLink(models.Model):  # TODO add this somehow
    book = models.ForeignKey(Book, db_column="book", on_delete=models.CASCADE)
    rating = models.ForeignKey(
        Rating, db_column="rating", on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'books_ratings_link'


class BookSeriesLink(models.Model):
    book = models.ForeignKey(Book, db_column="book", on_delete=models.CASCADE)
    series = models.ForeignKey(
        Series, db_column="series", on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'books_series_link'
        indexes = [
            models.Index(fields=["book"], name="books_series_link_bidx"),
            models.Index(fields=["series"], name="books_series_link_aidx"),
        ]


class BookTagLink(models.Model):

CalibreWebCompanion/library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import logging

logger = logging.getLogger(__name__)

class SearchForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200)
    author = forms.CharField(label='Author', max_length=100)
    identifier = forms.CharField(label='Identifier(ISBN, Google-id, amazon id)', max_length=20)
    generic = forms.CharField(label='All', max_length=100, required=False)



class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

CalibreWebCompanion/library/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <style>
    p.count {
      color: #FFFFFF;
      background-color: #515151;
      border: 1px #303030;
      border-radius: 0.5rem;
      padding: .2rem .25rem;
      margin: 0.1rem 0.1rem .1rem;

    }

    table {
      width: 100%;
      table-layout: fixed;
    }

    th {
      text-align: center;
    }

    .title {
      width: 30%;
    }

    .author {
      width: 20%;
    }

    .rating {
      width: 5%;
    }

    .tags {
      width: 25%;
    }

    .added {
      width: 10%;
    }

    .published {
      width: 10%;
    }
  </style>
</head>

<body>



  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper row green darken-1">

        <ul class="right">
          {% if user.is_authenticated %}
          <li class="active"><a href="{{user.get_absolute_url}}"> {{ user.get_username }}</a></li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        </ul>
        {% load cache %}
        {% cache 500 sidebar request.user.username %}
        <!--Maybe i'm retarded but this is not caching versions per user-->
        <ul class="left">
          <li><a href="{% url 'books' %}">Books</a></li>
          <li><a class="dropdown-trigger" href={% url 'authors' %} data-target="dropdown-authors">Authors<i
                class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-trigger" href={% url "ratings" %} data-target="dropdown-ratings">Ratings<i
                class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-trigger" href={% url "tags" %} data-target="dropdown-tags">Tags<i
                class="material-icons right">arrow_drop_down</i></a></li>

          <li><a class="dropdown-trigger" href={% url "series" %} data-target="dropdown-series">Series<i
                class="material-icons right">arrow_drop_down</i></a></li>

          <li><a class="dropdown-trigger" href={% url "publishers" %} data-target="dropdown-pubishers">Publishers<i
                class="material-icons right">arrow_drop_down</i></a></li>

          <li><a href="{% url 'search' %}">Advanced search</a></li>
          <li>
            <!-- stefan, this div. can we have this int the navbar? -->
            <div class="container">
              <form action="{% url 'results' %}" method="get" style="padding-top:2em">
                <label for="generic"></label>
                <input id="generic" type="text" name="generic" value="">
                <button class="waves-effect waves-light btn green accent-4" type="submit">search</button>
              </form>
            </div>
            <!-- this is the end of the div, stefan -->
          </li>
        </ul>
        <ul id="dropdown-authors" class="dropdown-content">
          {% for author in unique_authors %}
          <li><a href="{{author.get_absolute_url}}">{{author}}</a></li>
          {% endfor %}
        </ul>
        <ul id="dropdown-ratings" class="dropdown-content">
          {% for rating in unique_ratings %}
          <li><a href="{{rating.get_absolute_url}}">{{rating}}</a></li>
          {% endfor %}
        </ul>
        <ul id="dropdown-tags" class="dropdown-content">
          {% for tag in unique_tags %}
          <li><a href="{{tag.get_absolute_url}}">{{tag}} ({{tag.num_books}})</a></li>
          {% endfor %}
        </ul>

        <ul id="dropdown-series" class="dropdown-content">
          {% for tag in unique_series %}
          <li><a href="{{tag.get_absolute_url}}">{{tag}} ({{tag.num_books}})</a></li>
          {% endfor %}
        </ul>
        <ul id="dropdown-pubishers" class="dropdown-content">
          {% for pub in unique_publishers %}
          <!-- stefan here's my shit count  -->
          <li><a href="{{pub.get_absolute_url}}">{{pub}} <p class="count">{{pub.num_books}}</p> </a> </li>
          {% endfor %}
        </ul>
        {% endcache %}
        {% else %}
        <li><a href="{% url 'sign-up'%}?next={{request.path}}">Sign up</a></li>
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        </ul>
        {% endif %}
      </div>

    </nav>
  </div>
  <script>
    $(".dropdown-trigger").dropdown({
      hover: true,
      constrainWidth: false,
      coverTrigger: false
    });
  </script>

  {% if user.is_authenticated %}
  {% block content %} {% endblock %}
  {% else %}
  <div class="valign-wrapper" style="width:100%;height:100%;position: absolute;">
    <div class="valign" style="width:100%;">
      <div class="container">
        <div class="row">
          <div class="col s12 m6 offset-m3">
            <div class="card">
              <div class="card-content center">
                <p>You don't have permission to view this.</p>
              </div>
              <div class="card-action center">
                <a class="waves-effect waves-light btn-large green accent-4"
                  href="{% url 'login'%}?next={{request.path}}">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <script>
    function sortTable(n) {
      var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
      table = document.getElementById("books");
      switching = true;
      // Set the sorting direction to ascending:
      dir = "asc";
      /* Make a loop that will continue until
      no switching has been done: */
      while (switching) {
        // Start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        /* Loop through all table rows (except the
        first, which contains table headers): */
        for (i = 1; i < (rows.length - 1); i++) {
          // Start by saying there should be no switching:
          shouldSwitch = false;
          /* Get the two elements you want to compare,
          one from current row and one from the next: */
          x = rows[i].getElementsByTagName("TD")[n];
          y = rows[i + 1].getElementsByTagName("TD")[n];
          /* Check if the two rows should switch place,
          based on the direction, asc or desc: */
          if (dir == "asc") {
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
              // If so, mark as a switch and break the loop:
              shouldSwitch = true;
              break;
            }
          } else if (dir == "desc") {
            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
              // If so, mark as a switch and break the loop:
              shouldSwitch = true;
              break;
            }
          }
        }
        if (shouldSwitch) {
          /* If a switch has been marked, make the switch
          and mark that a switch has been done: */
          rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
          switching = true;
          // Each time a switch is done, increase this count by 1:
          switchcount++;
        } else {
          /* If no switching has been done AND the direction is "asc",
          set the direction to "desc" and run the while loop again. */
          if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
          }
        }
      }
    }
  </script>

</body>

</html>

CalibreWebCompanion/library/templates/ifelselogin.html
   {% if user.is_authenticated %}
   
   {% else %}
    <div class="valign-wrapper" style="width:100%;height:100%;position: absolute;">
      <div class="valign" style="width:100%;">
        <div class="container">
          <div class="row">
            <div class="col s12 m6 offset-m3">
              <div class="card">
                <div class="card-content center">
                  <p>You don't have permission to view this.</p> 
                </div>
                <div class="card-action center">
                  <a class="waves-effect waves-light btn-large green accent-4" href="{% url 'login'%}?next={{request.path}}">Login</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   {% endif %} 

CalibreWebCompanion/library/templates/results.html
{% extends "base.html" %}

{% block content %}

<h1>Results</h1>

<table id="books">
  <tr>
    <!--When a header is clicked, run the sortTable function, with a parameter, 0 for sorting by names, 1 for sorting by country:-->
    <th class="title" onclick="sortTable(0)">Title</th>
    <th class="author" onclick="sortTable(1)">Author</th>
    <th class="rating" onclick="sortTable(2)">Rating</th>
    <th class="tags" onclick="sortTable(3)">Tags</th>
    <th class="added" onclick="sortTable(4)">Added</th>
  </tr>
  {% for book in book_list %}
  <tr>
    <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
    <td>{{book.author_sort}}</td>
    <td> {% for rating in book.ratings.all %}
      {{rating}}
      {% endfor %}
    </td>
    <td>
      {% for tag in book.tags.all %}
      {{tag}},
      {% endfor %}
    </td>
    <td>{{book.timestamp}}</td>
  </tr>
  {% endfor %}
</table>







{% endblock %}

CalibreWebCompanion/library/templates/search.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<form action="{% url 'results' %}" method="get" style="padding-top:2em">
    <label for="title">Title: </label>
    <input id="title" type="text" name="title" value="">
    <label for="author">Author: </label>
    <input id="author" type="text" name="author" value="">
    <label for="author">Identifier: </label>
    <input id="identifier" type="text" name="identifier" value="">
    <button class="waves-effect waves-light btn green accent-4" type="submit">search</button>
</form>
</div>

{% endblock %}

CalibreWebCompanion/library/templates/stripped_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</head>

<body>

<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper row green darken-1">

      <ul class="right">
      {% if user.is_authenticated %}
        <li class="active"><a href="{{user.get_absolute_url}}"> {{ user.get_username }}</a></li>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
      </ul>
      {% else %}
        <li><a href="{% url 'sign-up'%}?next={{request.path}}">Sign up</a></li>
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
      </ul>
      {% endif %}
    </div>
  </nav>
</div>
<div class="container">
  <div class="row">
    <div class="col s10 ">{% block content %}{% endblock %}</div>
  </div>
</div>

</body>

</html>